version: '3.9'

services:
  api:
    container_name: jira_clone_api
    build: ./api
    depends_on:
      - db
    ports:
      - 8008:8000
    volumes:
      - ./api:/api
    environment:
      DB_USERNAME: mr_lx
      DB_PASSWORD: lx_is_lx
      DB_HOST: jira_clone_db
      DB_PORT: 5432
      DB_NAME: jira_clone

  db:
    container_name: jira_clone_db
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mr_lx
      POSTGRES_PASSWORD: lx_is_lx
      POSTGRES_DB: jira_clone

volumes:
  postgres_data:
